### ISSUE TITLE
Roswaalified text

### ISSUE THREAD

**Issue by sunekku** [itchono/Comrade#153]
Turns user message into Roswaal-sounding text.

Rules for Roswaal sounding things:

1. Only one stressed vowel per message
2. Occurs at the very end of a message
3. Silent vowels are not stressed
4. Alternate between capital letters and lower case letters in any way that you deem appropriate 
5. The last message sent can be Roswaalified with a user command

eg. Here is an example of something Roswaal would sAAAAaaaay (the exact sequence of capital and lower case letters does not need to follow this example)

Here is another exAAAaaample.

**Comment by itchono** [comment]
ImplEEEEeeemented
